// <auto-generated />
using System;
using ConciCarpinella.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConciCarpinella.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325235057_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConciCarpinella.API.Models.Autorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CantidadAutorizada")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<string>("DniPaciente")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUtilizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroAfiliado")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("PracticaId");

                    b.ToTable("Autorizaciones");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LimiteSesiones")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PeriodoLimite")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeCubierto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereAutorizacion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PracticaId");

                    b.HasIndex("PlanId", "PracticaId")
                        .IsUnique();

                    b.ToTable("Coberturas");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Concepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ContactoObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("ContactosObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Coseguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorFijo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Coseguros");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Nomenclador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nomencladores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasFilter("\"Cuit\" IS NOT NULL");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Practica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NomencladorId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NomencladorId");

                    b.HasIndex("Codigo", "NomencladorId")
                        .IsUnique();

                    b.ToTable("Practicas");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Traductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoDestino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NomencladorDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("NomencladorOrigenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomencladorDestinoId");

                    b.HasIndex("NomencladorOrigenId");

                    b.ToTable("Traductores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("PracticaId");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.VigenciaObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("VigenciasObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Autorizacion", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Cobertura", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Coberturas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("Coberturas")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ContactoObraSocial", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany("Contactos")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Coseguro", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Coseguros")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Plan", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany("Planes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Practica", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Nomenclador", "Nomenclador")
                        .WithMany("Practicas")
                        .HasForeignKey("NomencladorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nomenclador");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Traductor", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Nomenclador", "NomencladorDestino")
                        .WithMany("TraduccionesDestino")
                        .HasForeignKey("NomencladorDestinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Nomenclador", "NomencladorOrigen")
                        .WithMany("TraduccionesOrigen")
                        .HasForeignKey("NomencladorOrigenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NomencladorDestino");

                    b.Navigation("NomencladorOrigen");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Valor", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Valores")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("Valores")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.VigenciaObraSocial", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany("Vigencias")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Nomenclador", b =>
                {
                    b.Navigation("Practicas");

                    b.Navigation("TraduccionesDestino");

                    b.Navigation("TraduccionesOrigen");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ObraSocial", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Planes");

                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Plan", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Coberturas");

                    b.Navigation("Coseguros");

                    b.Navigation("Valores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Practica", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Coberturas");

                    b.Navigation("Valores");
                });
#pragma warning restore 612, 618
        }
    }
}
