// <auto-generated />
using System;
using ConciCarpinella.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConciCarpinella.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConciCarpinella.API.Models.Autorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CantidadAutorizada")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<string>("DniPaciente")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUtilizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroAfiliado")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("PracticaId");

                    b.ToTable("Autorizaciones");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LimiteSesiones")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PeriodoLimite")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeCubierto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereAutorizacion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PracticaId");

                    b.HasIndex("PlanId", "PracticaId")
                        .IsUnique();

                    b.ToTable("Coberturas");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Concepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ContactoObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("ContactosObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Coseguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorFijo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Coseguros");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ImportacionValores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aplicada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("ImportacionesValores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ImportacionValoresItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoExterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoPractica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescripcionPractica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ImportacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ValorImportado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImportacionId");

                    b.ToTable("ImportacionesValoresItems");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.NormaOpAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NormaId")
                        .HasColumnType("integer");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormaId");

                    b.ToTable("NormaOpAuditLogs");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.NormaOpOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("NormaOpOpciones");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.NormaOperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AceptaFotocopiaRp")
                        .HasColumnType("text");

                    b.Property<string>("AceptaPedidoDigitalPreimpreso")
                        .HasColumnType("text");

                    b.Property<bool?>("AceptaPedidoFirmaDigital")
                        .HasColumnType("boolean");

                    b.Property<string>("AceptaRpDigital")
                        .HasColumnType("text");

                    b.Property<string>("AnatomiaPatologica")
                        .HasColumnType("text");

                    b.Property<string>("Anestesias")
                        .HasColumnType("text");

                    b.Property<string>("CarnetDiscapacidadOncologico")
                        .HasColumnType("text");

                    b.Property<string>("Cirugia")
                        .HasColumnType("text");

                    b.Property<int?>("CodigoOs")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactoFacturacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<int?>("CopiasFacturasId")
                        .HasColumnType("integer");

                    b.Property<string>("Coseguros")
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<int?>("DireccionEntregaId")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("EfectorConsultasId")
                        .HasColumnType("integer");

                    b.Property<int?>("EfectorImagenId")
                        .HasColumnType("integer");

                    b.Property<string>("EfectorNoAparece")
                        .HasColumnType("text");

                    b.Property<int?>("EfectorOftalmologiaId")
                        .HasColumnType("integer");

                    b.Property<int?>("EfectorOtrasId")
                        .HasColumnType("integer");

                    b.Property<int?>("EstudiosValorCeroId")
                        .HasColumnType("integer");

                    b.Property<string>("FechaAutorizacion")
                        .HasColumnType("text");

                    b.Property<int?>("FechaCalculoVigenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FechaFacturacionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormatoAutorizacion")
                        .HasColumnType("text");

                    b.Property<string>("HorarioObraSocial")
                        .HasColumnType("text");

                    b.Property<string>("InformacionAdicional")
                        .HasColumnType("text");

                    b.Property<int?>("LaboratorioFacturaId")
                        .HasColumnType("integer");

                    b.Property<bool?>("LibreDeDeuda")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkDrive")
                        .HasColumnType("text");

                    b.Property<string>("LinkInstructivo")
                        .HasColumnType("text");

                    b.Property<string>("MedicoNoAparece")
                        .HasColumnType("text");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<int?>("ModoCierreId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreOs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacionesAutorizaciones")
                        .HasColumnType("text");

                    b.Property<string>("PaginaObraSocial")
                        .HasColumnType("text");

                    b.Property<string>("RequiereAutorizacionExpresa")
                        .HasColumnType("text");

                    b.Property<bool?>("SoporteMagnetico")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoAutorizacion")
                        .HasColumnType("text");

                    b.Property<int?>("TipoOrdenId")
                        .HasColumnType("integer");

                    b.Property<bool?>("TroquelContrastes")
                        .HasColumnType("boolean");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.Property<int?>("VigenciaOrdenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactoFacturacionId");

                    b.HasIndex("CopiasFacturasId");

                    b.HasIndex("DireccionEntregaId");

                    b.HasIndex("DocumentacionId");

                    b.HasIndex("EfectorConsultasId");

                    b.HasIndex("EfectorImagenId");

                    b.HasIndex("EfectorOftalmologiaId");

                    b.HasIndex("EfectorOtrasId");

                    b.HasIndex("EstudiosValorCeroId");

                    b.HasIndex("FechaCalculoVigenciaId");

                    b.HasIndex("FechaFacturacionId");

                    b.HasIndex("LaboratorioFacturaId");

                    b.HasIndex("ModoCierreId");

                    b.HasIndex("ObraSocialId");

                    b.HasIndex("TipoOrdenId");

                    b.HasIndex("VigenciaOrdenId");

                    b.ToTable("NormasOperativas");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasFilter("\"Cuit\" IS NOT NULL");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsAutogestion")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoIva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Practica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClasificadorPracticaId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("NomencladorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NomencladorId");

                    b.HasIndex("ClasificadorPracticaId");

                    b.HasIndex("NomencladorId", "Codigo")
                        .IsUnique();

                    b.ToTable("Practicas");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.PracticaConceptoUnidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("ConceptoMaestroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadArancelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Unidades")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PracticaId");

                    b.HasIndex("PracticaId", "ConceptoMaestroId");

                    b.ToTable("PracticaConceptoUnidades");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.PracticaAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string?>("DatosAnteriores")
                        .HasColumnType("text");

                    b.Property<string?>("DatosNuevos")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("PracticaConceptoUnidadId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("PracticaId");

                    b.ToTable("PracticaAuditLogs");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Traductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoDestino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NomencladorDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("NomencladorOrigenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomencladorDestinoId");

                    b.HasIndex("NomencladorOrigenId");

                    b.ToTable("Traductores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticaId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("PracticaId");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.VigenciaObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("VigenciasObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.VigenciaPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("VigenciasPlan");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Autorizacion", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Cobertura", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Coberturas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("Coberturas")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ContactoObraSocial", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany("Contactos")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Coseguro", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Coseguros")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ImportacionValores", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ImportacionValoresItem", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ImportacionValores", "Importacion")
                        .WithMany("Items")
                        .HasForeignKey("ImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacion");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.NormaOperativa", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "ContactoFacturacion")
                        .WithMany()
                        .HasForeignKey("ContactoFacturacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "CopiasFacturas")
                        .WithMany()
                        .HasForeignKey("CopiasFacturasId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "DireccionEntrega")
                        .WithMany()
                        .HasForeignKey("DireccionEntregaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "Documentacion")
                        .WithMany()
                        .HasForeignKey("DocumentacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "EfectorConsultas")
                        .WithMany()
                        .HasForeignKey("EfectorConsultasId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "EfectorImagen")
                        .WithMany()
                        .HasForeignKey("EfectorImagenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "EfectorOftalmologia")
                        .WithMany()
                        .HasForeignKey("EfectorOftalmologiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "EfectorOtras")
                        .WithMany()
                        .HasForeignKey("EfectorOtrasId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "EstudiosValorCero")
                        .WithMany()
                        .HasForeignKey("EstudiosValorCeroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "FechaCalculoVigencia")
                        .WithMany()
                        .HasForeignKey("FechaCalculoVigenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "FechaFacturacion")
                        .WithMany()
                        .HasForeignKey("FechaFacturacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "LaboratorioFactura")
                        .WithMany()
                        .HasForeignKey("LaboratorioFacturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "ModoCierre")
                        .WithMany()
                        .HasForeignKey("ModoCierreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "TipoOrden")
                        .WithMany()
                        .HasForeignKey("TipoOrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NormaOpOpcion", "VigenciaOrden")
                        .WithMany()
                        .HasForeignKey("VigenciaOrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContactoFacturacion");

                    b.Navigation("CopiasFacturas");

                    b.Navigation("DireccionEntrega");

                    b.Navigation("Documentacion");

                    b.Navigation("EfectorConsultas");

                    b.Navigation("EfectorImagen");

                    b.Navigation("EfectorOftalmologia");

                    b.Navigation("EfectorOtras");

                    b.Navigation("EstudiosValorCero");

                    b.Navigation("FechaCalculoVigencia");

                    b.Navigation("FechaFacturacion");

                    b.Navigation("LaboratorioFactura");

                    b.Navigation("ModoCierre");

                    b.Navigation("ObraSocial");

                    b.Navigation("TipoOrden");

                    b.Navigation("VigenciaOrden");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Plan", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany("Planes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Practica", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ClasificadorPractica", "ClasificadorPractica")
                        .WithMany()
                        .HasForeignKey("ClasificadorPracticaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConciCarpinella.API.Models.NomencladorMaestro", "NomencladorMaestro")
                        .WithMany()
                        .HasForeignKey("NomencladorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClasificadorPractica");

                    b.Navigation("NomencladorMaestro");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.PracticaConceptoUnidad", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ConceptoMaestro", "ConceptoMaestro")
                        .WithMany()
                        .HasForeignKey("ConceptoMaestroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("ConceptoUnidades")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.UnidadArancel", "UnidadArancel")
                        .WithMany()
                        .HasForeignKey("UnidadArancelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConceptoMaestro");

                    b.Navigation("Practica");

                    b.Navigation("UnidadArancel");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.PracticaAuditLog", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Traductor", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.NomencladorMaestro", "NomencladorDestino")
                        .WithMany()
                        .HasForeignKey("NomencladorDestinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.NomencladorMaestro", "NomencladorOrigen")
                        .WithMany()
                        .HasForeignKey("NomencladorOrigenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NomencladorDestino");

                    b.Navigation("NomencladorOrigen");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Valor", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Valores")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConciCarpinella.API.Models.Practica", "Practica")
                        .WithMany("Valores")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.VigenciaObraSocial", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.ObraSocial", "ObraSocial")
                        .WithMany("Vigencias")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.VigenciaPlan", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.Plan", "Plan")
                        .WithMany("Vigencias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ImportacionValores", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.ObraSocial", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Planes");

                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Plan", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Coberturas");

                    b.Navigation("Coseguros");

                    b.Navigation("Valores");

                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.Practica", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Coberturas");

                    b.Navigation("Valores");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.UnidadArancel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("UnidadesArancel");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.UnidadArancelAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool?>("ActivoAnterior")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ActivoNuevo")
                        .HasColumnType("boolean");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreAnterior")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreNuevo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnidadArancelId")
                        .HasColumnType("integer");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("VigenciaDesdeAnterior")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaDesdeNuevo")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaHastaAnterior")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaHastaNuevo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UnidadArancelId");

                    b.ToTable("UnidadesArancelAuditLog");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.UnidadArancelAuditLog", b =>
                {
                    b.HasOne("ConciCarpinella.API.Models.UnidadArancel", "UnidadArancel")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UnidadArancelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadArancel");
                });

            modelBuilder.Entity("ConciCarpinella.API.Models.UnidadArancel", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
